{
 "title": "[ API ] Prometheus-RDS-Exporter",
 "description": "RDS exporter",
 "tags": [
  "rds",
  "exporter",
  "database_misc"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(rds_exporter_build_info,instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporters total",
   "type": "stat",
   "description": "Number of Prometheus RDS exporter",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rds_exporter_build_info{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporters status",
   "type": "stat",
   "description": "Status over time",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{} * on (instance) rds_exporter_build_info{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of errors",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rds_exporter_errors_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AWS accounts",
   "type": "stat",
   "description": "Number of AWS accounts found by the exporter",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    sum by (aws_account_id) (rds_instance_info{instance=~\"$instance\"})\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "AWS RDS instances",
   "type": "stat",
   "description": "Number of RDS instances found by the exporter",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rds_instance_info{instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RDS exporters",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rds_exporter_build_info{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AWS API calls per minute",
   "type": "timeseries",
   "description": "Number of call to AWS API",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(rds_api_call_total{instance=~\"$instance\"}[5m]) * 60) by (api)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AWS API calls",
   "type": "stat",
   "description": "Total of AWS API calls",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(rds_api_call_total{instance=~\"$instance\"}) by (api)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "description": "Number of RDS exporter errors per minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(rds_exporter_errors_total{instance=~\"$instance\"}[1m]) * 60) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}