{
 "title": "[ PRD ] MySQL Real-time Session & Process",
 "description": "세션 및 프로세스 모니터링",
 "tags": [
  "DB",
  "Aurora",
  "MySQL",
  "Status"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "[ Millie-PRD ] Process List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Millie-PRD-instance-2 :: Process List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT `ID`, `USER`, `HOST`, `DB`, `COMMAND`, `TIME`, `STATE`, `INFO` AS `SQL` FROM `information_schema`.`PROCESSLIST`\nwhere info is not null\nand DB <> 'information_schema'\nand user <> 'monitor'\norder by `time` desc;"
    }
   ]
  },
  {
   "title": "Millie-PRD-instance-3 :: Process List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT `ID`, `USER`, `HOST`, `DB`, `COMMAND`, `TIME`, `STATE`, `INFO` AS `SQL` FROM `information_schema`.`PROCESSLIST`\nwhere info is not null\nand DB <> 'information_schema'\nand user <> 'monitor'\norder by `time` desc;"
    }
   ]
  },
  {
   "title": "[ Millie-PRD ] Transaction Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Transaction Monitoring",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n\t    b.id as PID,\n\t    a.trx_id, \n      a.trx_state, \n      a.trx_started,\n      TIMESTAMPDIFF(SECOND,a.trx_started, now()) as \"TRX OPEN TIME\",\n      b.time as \"TIME\", \n      a.trx_rows_modified, \n      b.USER, \n      b.host, \n      b.db, \n      b.command, \n      b.state,\n      a.trx_query\nFROM  information_schema.innodb_trx a, \n      information_schema.processlist b \nWHERE a.trx_mysql_thread_id=b.id\n  and command != 'sleep'\n  AND TIMESTAMPDIFF(SECOND,a.trx_started, now()) > 10 \nORDER BY trx_started;"
    }
   ]
  },
  {
   "title": "Transaction Lock",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  r.trx_id as \"Waiting Trx ID\",\n  r.trx_mysql_thread_id as \"Waiting Thread\",\n  r.trx_query as \"Waiting Query\",\n  b.trx_id as \"Blocking Trx ID\",\n  b.trx_mysql_thread_id as \"Blocking Thread\",\n  b.trx_query as \"Blocking Query\"\nFROM       information_schema.innodb_lock_waits w\nINNER JOIN information_schema.innodb_trx b ON b.trx_id = w.blocking_trx_id\nINNER JOIN information_schema.innodb_trx r ON r.trx_id = w.requesting_trx_id;"
    }
   ]
  },
  {
   "title": "[ Millie-PRD-Others ] Process List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Millie-PRD-Statistics-RW :: Process List",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT `ID`, `USER`, `HOST`, `DB`, `COMMAND`, `TIME`, `STATE`, `INFO` AS `SQL` FROM `information_schema`.`PROCESSLIST`\nwhere info is not null\nand DB <> 'information_schema'\nand user <> 'monitor'\norder by `time` desc;"
    }
   ]
  },
  {
   "title": "Millie-PRD-Service-Log-RW :: Process List",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT `ID`, `USER`, `HOST`, `DB`, `COMMAND`, `TIME`, `STATE`, `INFO` AS `SQL` FROM `information_schema`.`PROCESSLIST`\nwhere info is not null\nand DB <> 'information_schema'\nand user <> 'monitor'\norder by `time` desc;"
    }
   ]
  }
 ]
}