{
 "title": "[ RDS ] Replication",
 "description": "Replication Status",
 "tags": [
  " aws",
  "rds",
  "database_server"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "aws_account_id",
    "label": "account",
    "query": {
     "query": "label_values(rds_instance_info,aws_account_id)"
    }
   },
   {
    "name": "aws_region",
    "label": "region",
    "query": {
     "query": "label_values(rds_instance_info{aws_account_id=~\"$aws_account_id\"},aws_region)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Replica Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "replica-db.millietown.com :: Replica Configration",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n\tHOST,\n\tPORT,\n\t`USER`,\n\tAUTO_POSITION,\n\tCONNECTION_RETRY_INTERVAL,\nCONNECTION_RETRY_COUNT,\nHEARTBEAT_INTERVAL\nFROM performance_schema.replication_connection_configuration;"
    }
   ]
  },
  {
   "title": "data-analysis.millietown.com :: Replica Configration",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n\tHOST,\n\tPORT,\n\t`USER`,\n\tAUTO_POSITION,\n\tCONNECTION_RETRY_INTERVAL,\nCONNECTION_RETRY_COUNT,\nHEARTBEAT_INTERVAL\nFROM performance_schema.replication_connection_configuration;"
    }
   ]
  },
  {
   "title": "replica-db.millietown.com :: Replica Master Relay Log Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT Master_log_name, Master_log_pos, Relay_log_name , Relay_log_pos ,Sql_delay  FROM mysql.slave_relay_log_info;"
    }
   ]
  },
  {
   "title": "data-analysis.millietown.com :: Replica Master Relay Log Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT Master_log_name, Master_log_pos, Relay_log_name , Relay_log_pos ,Sql_delay  FROM mysql.slave_relay_log_info;"
    }
   ]
  },
  {
   "title": "replica-db.millietown.com :: Replica Process Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT command, state FROM information_schema.PROCESSLIST\nWHERE `USER` = 'system user';"
    }
   ]
  },
  {
   "title": "data-analysis.millietown.com :: Replica Process Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT command, state FROM information_schema.PROCESSLIST\nWHERE `USER` = 'system user';"
    }
   ]
  },
  { "title": "Binlog Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Binary Log Files",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cloud_exporter_NumBinaryLogFiles{job=\"rds_exporter\", statistics=\"max\", exported_instance=~\"millie-prd-instance-3|millie-prd-replica-instance-1|millie-prd-service-log-instance-2\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Binary Log Size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cloud_exporter_SumBinaryLogSize{job=\"rds_exporter\", statistics=\"max\", exported_instance=~\"millie-prd-instance-3|millie-prd-replica-instance-1|millie-prd-service-log-instance-2\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "millie-data-analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } }
 ]
}