{
 "title": "[ RDS ] instance details",
 "description": "AWS RDS instance",
 "tags": [
  "aws",
  "rds",
  "database_server"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "aws_account_id",
    "label": "account",
    "query": {
     "query": "label_values(rds_instance_info,aws_account_id)"
    }
   },
   {
    "name": "aws_region",
    "label": "region",
    "query": {
     "query": "label_values(rds_instance_info{aws_account_id=\"$aws_account_id\"},aws_region)"
    }
   },
   {
    "name": "dbidentifier",
    "query": {
     "query": "label_values(rds_instance_info{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\"},dbidentifier)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Engine",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engine version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "{{engine_version}}"
    }
   ]
  },
  {
   "title": "Instance class",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "{{engine_version}}"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    max(rds_instance_vcpu_average{}) by (instance_class)\n    * on (instance_class)\n    group_left(dbidentifier)\n    max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (aws_account_id, aws_region, dbidentifier, instance_class)\n)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    max(rds_instance_memory_bytes{}) by (instance_class)\n    * on (instance_class)\n    group_left(aws_account_id,aws_region,dbidentifier)\n    max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (aws_account_id, aws_region, dbidentifier, instance_class)\n)"
    }
   ]
  },
  {
   "title": "Storage type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "{{engine_version}}"
    }
   ]
  },
  {
   "title": "Multi-AZ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "{{engine_version}}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Time since instance creation",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_age_seconds{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=\"$dbidentifier\", instance=\"localhost:9043\"}"
    }
   ]
  },
  {
   "title": "Engine UpTime",
   "type": "stat",
   "description": "DB 재구동 후 가동 시간",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_engine_uptime_seconds{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", instance=\"localhost:9043\", dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_status{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}"
    }
   ]
  },
  {
   "title": "Pending modification",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "{{pending_modified_values}}"
    }
   ]
  },
  {
   "title": "Pending maintenance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "{{pending_maintenance}}"
    }
   ]
  },
  {
   "title": "CA certificate identifier",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dbi resource id",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup retention",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rds_backup_retention_period_seconds{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rds_cpu_usage_percent_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - sum(rds_freeable_memory_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier) * 100 / sum(rds_instance_memory_bytes{} * on (instance_class) group_left(dbidentifier) rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_database_connections_average{dbidentifier=\"$dbidentifier\", instance=\"localhost:9043\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Cache Hit Ratio (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_buffer_cache_hit_ratio{dbidentifier=\"$dbidentifier\", instance=\"localhost:9043\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_queries{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=\"$dbidentifier\", instance=\"localhost:9043\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Ratio of CPU usage",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rds_cpu_usage_percent_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Active queries vs vCPU",
   "type": "timeseries",
   "description": "Number of active queries waiting for CPU or not. For optimal performances, should not have more CPU wait that number of CPU",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "max(rds_dbload_cpu_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "CPU wait"
    },
    {
     "expr": "max(rds_dbload_noncpu_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Non CPU wait"
    },
    {
     "expr": "max(\n    max(rds_instance_vcpu_average{}) by (instance_class)\n    * on (instance_class)\n    group_left(aws_account_id,aws_region,dbidentifier)\n    max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (aws_account_id, aws_region, dbidentifier, instance_class)\n)",
     "legendFormat": "Number of vCPU"
    }
   ]
  },
  {
   "title": "Buffer Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rds_buffer_cache_hit_ratio{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=\"$dbidentifier\", instance=\"localhost:9043\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "The amount of available random access memory",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rds_freeable_memory_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Freeable"
    },
    {
     "expr": "100\n- max(rds_freeable_memory_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)\n* 100\n/ on(dbidentifier) (\n    max(rds_instance_memory_bytes{}) by (instance_class)\n    * on (instance_class)\n    group_right()\n    max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier, instance_class)\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(\n    max(rds_instance_memory_bytes{}) by (instance_class)\n    * on (instance_class)\n    group_left(dbidentifier) max(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier, instance_class)\n)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rds_deadlocks{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=\"$dbidentifier\", instance=\"localhost:9043\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Disk IOPS usage",
   "type": "timeseries",
   "description": "Total of read and write disk IOPS regarding instance IOPS limits ",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 25 },
   "targets": [
    {
     "expr": "max(rds_read_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "max(rds_write_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "max(rds_max_disk_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "max((rds_read_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"} + rds_write_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) * 100 / rds_max_disk_iops_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Command History",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.*.command" },
      { "jsonPath": "$.*.total", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.*.avgForHours", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.*.avgForSeconds", "language": "jsonpath", "name": "" },
      { "jsonPath": "$.*.percentage", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "urlPath": "?instance_name=${dbidentifier}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rds_queries{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", instance=\"localhost:9043\", dbidentifier=\"$dbidentifier\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "timeseries",
   "description": "The average number of bytes read/write from disk per second",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rds_read_throughput_bytes{dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "max(rds_write_throughput_bytes{dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "max(rds_max_storage_throughput_bytes{dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "max((rds_read_throughput_bytes{dbidentifier=\"$dbidentifier\"} + rds_write_throughput_bytes{dbidentifier=\"$dbidentifier\"}) * 100 / rds_max_storage_throughput_bytes{dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "description": "The number of client network connections to the database instance",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "max by(dbidentifier) (rds_database_connections_average{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=\"$dbidentifier\", instance=\"localhost:9043\"})",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "description": "Storage size per type\nWAL only applied to PostgreSQL",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rds_free_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "max(rds_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(rds_instance_log_files_size_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Logs"
    },
    {
     "expr": "max(rds_replication_slot_disk_usage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Replication slots"
    },
    {
     "expr": "max(rds_transaction_logs_disk_usage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "description": "Amount of swap space used on the DB instance",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rds_swap_usage_bytes{dbidentifier=\"$dbidentifier\"}) by (dbidentifier)",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Used storage",
   "type": "timeseries",
   "description": "Ratio of free disk space",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(100 - rds_free_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"} * 100 / rds_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "RDS storage autoscaling usage",
   "type": "timeseries",
   "description": "If RDS storage autoscaling is enabled, display the current usage",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rds_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"} * 100 / rds_max_allocated_storage_bytes{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})",
     "legendFormat": "Autoscaling storage usage"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "description": "RDS instance status, when not in \"available\" some operations could not be possible",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 60 },
   "targets": [
    {
     "expr": "max(rds_instance_status{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"})"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used transactions",
     "type": "timeseries",
     "description": "The number of transactions currently used. Hard limit to 2 billion transactions (See Transaction ID Wraparound)",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "max(rds_maximum_used_transaction_ids_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",dbidentifier=\"$dbidentifier\"}) by (dbidentifier)",
       "legendFormat": "{{dbidentifier}}"
      }
     ]
    },
    {
     "title": "Replication lag",
     "type": "timeseries",
     "description": "Lag of PostgreSQL replica instances",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rds_replica_lag_seconds{}) by (dbidentifier)\n* on (dbidentifier)\ngroup_left(source_dbidentifier)\nmax(rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",source_dbidentifier=\"$dbidentifier\"}) by (dbidentifier)",
       "legendFormat": "{{dbidentifier}}"
      }
     ]
    }
   ]
  }
 ]
}