{
 "title": "[ RDS ] instances",
 "description": "Inventory of RDS instances",
 "tags": [
  "aws",
  "rds",
  "inventory",
  "database_server"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "aws_account_id",
    "label": "account",
    "query": {
     "query": "label_values(rds_instance_info,aws_account_id)"
    }
   },
   {
    "name": "aws_region",
    "label": "region",
    "query": {
     "query": "label_values(rds_instance_info{aws_account_id=~\"$aws_account_id\"},aws_region)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "datasource" },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rds_cpu_usage_percent_average{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=~\"millie-prd-instance-2|millie-prd-instance-3|millie-prd-replica-instance-1\"}",
     "legendFormat": "{{dbidentifier}}"
    },
    {
     "expr": "rds_cpu_usage_percent_average{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier!~\"millie-prd-instance-2|millie-prd-instance-3|millie-prd-replica-instance-1\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_database_connections_average{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=~\"millie-prd-instance-3|millie-prd-instance-2\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "Instance status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "rds_instance_status{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=~\"millie-prd-instance-3|millie-prd-instance-2|millie-prd-replica-instance-1\"}",
     "legendFormat": "{{dbidentifier}}"
    },
    {
     "expr": "rds_instance_status{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=~\"millie-prd-service-log-instance-1|millie-prd-service-log-instance-2|millie-prd-statistics-instance-1|millie-prd-statistics-instance-2\"}",
     "legendFormat": "{{dbidentifier}}"
    },
    {
     "expr": "rds_instance_status{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", dbidentifier=~\"millie-prd-biztalk-instance-1|millie-prd-biztalk-instance-2|millie-prd-company-instance-1\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rds_queries{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", instance=\"localhost:9043\", dbidentifier=~\"millie-prd-instance-3|millie-prd-instance-2\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rds_database_connections_average{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", instance=\"localhost:9043\", dbidentifier=~\"millie-prd-instance-3|millie-prd-instance-2\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rds_queries{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", instance=\"localhost:9043\", dbidentifier=~\"millie-prd-instance-3|millie-prd-instance-2\"}",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"})",
     "legendFormat": "RDS instances"
    }
   ]
  },
  {
   "title": "Instances with pending maintenances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",pending_maintenance!=\"no\"} > 0)"
    }
   ]
  },
  {
   "title": "Instances with pending modification",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",pending_modified_values!=\"false\"})"
    }
   ]
  },
  {
   "title": "Instances with deprecated certificate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\", ca_certificate_identifier!=\"rds-ca-rsa2048-g1\"})"
    }
   ]
  },
  {
   "title": "High RDS instance quota usage",
   "type": "gauge",
   "description": "AWS account & region with high RDS instance quota usage",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)\n* 100\n/\nsum(\n    max(rds_quota_max_dbinstances_average{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region) > 80",
     "legendFormat": "{{ aws_account_id }}:{{ aws_region }}"
    }
   ]
  },
  {
   "title": "High storage quota usage",
   "type": "gauge",
   "description": "AWS account & region with high storage quota usage",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    max(rds_allocated_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)\n* 100\n/\nsum(\n    max(rds_quota_total_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region) > 80",
     "legendFormat": "{{ aws_account_id }}:{{ aws_region}}"
    }
   ]
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "RDS Aurora for MySQL Cluster",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.*.Environment", "name": "Env" },
      { "jsonPath": "$.*.region", "language": "jsonpath", "name": "Region" },
      { "jsonPath": "$.*.DBClusterIdentifier", "language": "jsonpath", "name": "Aurora Cluster Name" },
      { "jsonPath": "$.*.DBInstanceIdentifier", "language": "jsonpath", "name": "Instance Name" },
      { "jsonPath": "$.*.IsClusterWriter", "language": "jsonpath", "name": "Read / Write" },
      { "jsonPath": "$.*.EngineVersion", "language": "jsonpath", "name": "Engine Version" },
      { "jsonPath": "$.*.DBInstanceClass", "language": "jsonpath", "name": "Instance Class" },
      { "jsonPath": "$.*.DBInstanceStatus", "language": "jsonpath", "name": "Status" },
      { "jsonPath": "$.*.MultiAZ", "language": "jsonpath", "name": "Multi AZ" },
      { "jsonPath": "$.*.AvailabilityZone", "language": "jsonpath", "name": "Availability Zone" },
      { "jsonPath": "$.*.DeletionProtection", "language": "jsonpath", "name": "Del Protection" },
      { "jsonPath": "$.*.ClusterCreateTime", "language": "jsonpath", "name": "Cluster Create Time", "type": "time" },
      { "jsonPath": "$.*.InstanceCreateTime", "language": "jsonpath", "name": "Instance Create Time", "type": "time" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "RDS instances",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",} * on (dbidentifier) group_left max(rds_allocated_storage_bytes{}) by (dbidentifier)"
    }
   ]
  },
  { "title": "Pending operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Instances with pending maintenance",
   "type": "table",
   "description": "Instances that need to be restarted to apply AWS maintenance",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",pending_maintenance!=\"no\"}"
    }
   ]
  },
  {
   "title": "Instances with pending modification",
   "type": "table",
   "description": "Instances that need to be restarted to apply modification",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",pending_modified_values!=\"false\"}"
    }
   ]
  },
  {
   "title": "AWS Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDS instance quota usage (ratio)",
     "type": "timeseries",
     "description": "RDS 인스턴스 할당량과 관련된 인스턴스 수입니다. AWS에 쿼터 증량을 요청할 수 있습니다.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "count(\n    count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)\n* 100\n/\nsum(\n    max(rds_quota_max_dbinstances_average{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region)",
       "legendFormat": "{{ aws_account_id }}:{{ aws_region }}"
      }
     ]
    },
    {
     "title": "RDS storage quota usage (ratio)",
     "type": "timeseries",
     "description": "RDS 총 스토리지 할당량과 관련하여 사용된 총 스토리지입니다. AWS에 쿼터 증량을 요청할 수 있습니다.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(\n    max(rds_allocated_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)\n* 100\n/\nsum(\n    max(rds_quota_total_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region)",
       "legendFormat": "{{ aws_account_id }}:{{ aws_region }}"
      }
     ]
    },
    {
     "title": "RDS instance quota usage",
     "type": "timeseries",
     "description": "RDS 인스턴스 할당량과 관련된 인스턴스 수입니다. AWS에 쿼터 증량을 요청할 수 있습니다.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "count(\n    count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)",
       "legendFormat": "RDS instances - {{ aws_account_id }}:{{ aws_region }}"
      },
      {
       "expr": "sum(\n    max(rds_quota_max_dbinstances_average{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region)",
       "legendFormat": "Max - {{ aws_account_id }}:{{ aws_region }}"
      }
     ]
    },
    {
     "title": "RDS storage quota usage",
     "type": "timeseries",
     "description": "RDS 총 스토리지 할당량과 관련하여 사용된 총 스토리지입니다. AWS에 쿼터 증량을 요청할 수 있습니다.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    max(rds_allocated_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)",
       "legendFormat": "Total storage - {{ aws_account_id }}:{{ aws_region }}"
      },
      {
       "expr": "sum(\n    max(rds_quota_total_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region)",
       "legendFormat": "Max - {{ aws_account_id }}:{{ aws_region }}"
      }
     ]
    }
   ]
  }
 ]
}